In [1]:
import geopandas as gpd

In [3]:
green_scores = gpd.read_file('Choice_Green_scores/London_choice_green_scores_V2.shp')

In [4]:
green_scores

,GSS_CODE,NAME,green_gsv,green_gsv_,green_gs_1,mean_choic,median_cho,std_choice,green_gs_2,area_sqkm,...,ward_area,percent_on,percent_to,sat_all_wa,green_area,sat_ward_g,on_vs_off_,on_vs_of_1,sat_all__1,geometry
0,E05000026,Abbey,10.524896,10.687261,10.687261,14.176203,13.855123,5.704466,68.095426,1.28292,...,1282920.0,0.036192,0.2784,0.242208,0.003107,0.000414,2.181717,8.194326,23.872876,"POLYGON ((544735.197 184076.498, 544726.597 18..."
1,E05000027,Alibon,10.102674,10.269987,10.269987,9.614580,8.563932,4.634217,70.179522,1.36442,...,1364420.0,0.043492,0.4594,0.415908,0.005675,0.000756,1.146728,4.184326,44.305686,"POLYGON ((547932.401 184916.597, 547944.801 18..."
2,E05000028,Becontree,10.891959,11.220406,11.220406,12.623284,13.285051,6.332820,89.797771,1.28809,...,1288090.0,0.059345,0.3608,0.301455,0.003883,0.000518,1.806783,6.741666,30.842296,"POLYGON ((546209.397 185783.599, 546219.300 18..."
3,E05000029,Chadwell Heath,16.489458,16.415619,16.415619,8.776464,9.297543,5.033655,108.994082,3.38422,...,3384220.0,0.022585,0.6201,0.597515,0.020221,0.002695,0.525252,1.776460,65.668712,"POLYGON ((548874.201 188496.302, 548843.200 18..."
4,E05000030,Eastbrook,9.190002,9.635628,9.635628,7.141968,7.007301,5.072869,38.705019,3.45060,...,3450600.0,0.013875,0.5577,0.543825,0.018765,0.002501,0.315450,0.963595,59.352986,"POLYGON ((549991.498 184928.504, 549988.900 18..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,E05011485,South Norwood,15.143631,15.672658,15.672658,10.158616,9.981064,5.413939,126.515198,2.14118,...,2141180.0,0.027931,0.3197,0.291769,0.006247,0.000833,1.561372,5.790838,29.702900,"POLYGON ((533192.804 166825.795, 533214.604 16..."
628,E05011486,Thornton Heath,9.787341,11.057130,11.057130,11.122138,9.440416,6.543160,62.651055,1.72422,...,1724220.0,0.030782,0.3363,0.305518,0.005268,0.000702,1.196753,4.378147,31.320173,"POLYGON ((531555.599 169063.195, 531581.002 16..."
629,E05011487,Waddon,20.575712,19.467804,19.467804,10.478442,10.426035,6.255236,122.734638,3.91981,...,3919810.0,0.028446,0.4028,0.374354,0.014674,0.001956,0.903186,3.240738,39.417538,"POLYGON ((531218.598 162415.198, 531223.100 16..."
630,E05011488,West Thornton,11.665413,12.053162,12.053162,10.011314,9.261411,5.189101,75.968217,1.97117,...,1971170.0,0.020357,0.3284,0.308043,0.006072,0.000809,1.237468,4.535892,31.617219,"POLYGON ((530025.703 167330.601, 530020.203 16..."
631,E05011489,Woodside,12.197760,12.119307,12.119307,10.667424,10.618681,6.127112,80.288245,2.15022,...,2150220.0,0.020672,0.4209,0.400228,0.008606,0.001147,0.912976,3.278668,42.461194,"POLYGON ((535516.501 168006.797, 535511.703 16..."

In [ ]:
green_scores.columns